[tox]
min_version = 4.0
env_list = py{312,313,314}-{min,latest}

[testenv]
description = run the installed package tests with pytest
package = sdist-wheel
wheel_build_env = .pkg
extras = dev
set_env =
    py312-min: PIP_CONSTRAINT={tox_root}/requirements-testing/py312-min.txt
    py312-min: PIP_BUILD_CONSTRAINT={tox_root}/requirements-testing/py312-min.txt
    py313-min: PIP_CONSTRAINT={tox_root}/requirements-testing/py313-min.txt
    py313-min: PIP_BUILD_CONSTRAINT={tox_root}/requirements-testing/py313-min.txt
    py314-min: PIP_CONSTRAINT={tox_root}/requirements-testing/py314-min.txt
    py314-min: PIP_BUILD_CONSTRAINT={tox_root}/requirements-testing/py314-min.txt
    latest: PIP_CONSTRAINT={tox_root}/requirements-testing/latest.txt
    latest: PIP_BUILD_CONSTRAINT={tox_root}/requirements-testing/latest.txt
commands =
    python -c "import probabilisticnn; print(probabilisticnn.__file__)"
    pytest {tty:--color=yes} {posargs}
